### ISSUE TITLE
Lagoon post-2.0 API TODO List

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#2285]
This issue will be an updated list of changes still needed in the API for lagoon 2.0.

**DeploymentTarget (Openshift > Kubernetes)**

- [ ] - Add new api-db tables for kubernetes
- [ ] - Add mutations for CRUD kubernetes
- [ ] - Add migration for data in api-db (openshift > kubernetes)
- [ ] - Change all api references from openshift > deploymenttarget
- [ ] - Change all api external code that depends on "openshift"

**DeploymentTargetRules**

- [ ] - Add new api-db tables
- [ ] - Add mutations for CRUD rules
- [ ] - Add mutations for linking to projects
- [ ] - Change code that determines where an environment gets deployed

**Project**

- [ ] - Remove active systems settings and change all code to now reference the DeploymentTarget api type (for openshift/k8s)
- [ ] - Are there any projects that have mixed active systems settings? What kind of migration is needed for this change?

**Environment**

- [ ] - Generate unique name on add? does it change on dependency updates?
- [ ] - finalize "deploymetTargetId" name

**environmentByDeploymentTargetId**

- [ ] - Can we switch from searching by "namespace name" to unique id?
- [ ]     - Maybe not because k8s only knows the "namespace name"?
- [ ] - Update everything that searches by this to use unique name instead
- [ ] - At the least the UI can use a diff query? If we can't get rid of it, then UI changes can wait

**Comment by smlx** [comment]
Hi @rocketeerbkw I wonder if there's any way we could also get this feature request in? https://github.com/amazeeio/lagoon/issues/2181

I've had a look at the permissions system but I don't think I understand it well enough to tackle the implementation myself. And I really don't know how much work it would be. What are your thoughts?

**Comment by tobybellwood** [comment]
The rename from Openshift to DeployTarget is still in progress
